
-- Table: px3Joint
CREATE TABLE px3Joint ( 
    id                  INTEGER PRIMARY KEY,
    name                VARCHAR,
    jointType           INTEGER,
    twistLimit          REAL,
    swingLimit          REAL,
    swingLimit2         REAL,
    xLimit         	REAL,
    yLimit         	REAL,
    zLimit         	REAL,
    localAxis_x         REAL,
    localAxis_y         REAL,
    localAxis_z         REAL,
    localNormal_x       REAL,
    localNormal_y       REAL,
    localNormal_z       REAL,
    swingSpring         REAL,
    twistSpring         REAL,
    springDamper        REAL,
    motorSpring         REAL,
    motorDamper         REAL,
    maxForce            REAL,
    maxTorque           REAL,
    numLimitPlanes      INTEGER,
    limitPoint_x        REAL,
    limitPoint_y        REAL,
    limitPoint_z        REAL,
    limitPlaneAnchor1_x REAL,
    limitPlaneAnchor1_y REAL,
    limitPlaneAnchor1_z REAL,
    limitPlaneNormal1_x REAL,
    limitPlaneNormal1_y REAL,
    limitPlaneNormal1_z REAL,
    limitPlaneAnchor2_x REAL,
    limitPlaneAnchor2_y REAL,
    limitPlaneAnchor2_z REAL,
    limitPlaneNormal2_x REAL,
    limitPlaneNormal2_y REAL,
    limitPlaneNormal2_z REAL,
    limitPlaneAnchor3_x REAL,
    limitPlaneAnchor3_y REAL,
    limitPlaneAnchor3_z REAL,
    limitPlaneNormal3_x REAL,
    limitPlaneNormal3_y REAL,
    limitPlaneNormal3_z REAL,
    limitPlaneAnchor4_x REAL,
    limitPlaneAnchor4_y REAL,
    limitPlaneAnchor4_z REAL,
    limitPlaneNormal4_x REAL,
    limitPlaneNormal4_y REAL,
    limitPlaneNormal4_z REAL
);

